name: Release on tag

on:
  push:
    tags: [ '*' ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Get tag version
      id: tag
      shell: bash
      run: echo "VERSION=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_OUTPUT

    - uses: actions/checkout@v4

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Publish with dotnet
      run: |
        dotnet publish AutoMidiPlayer.WPF -r win-x64 -c Release -o .\install --self-contained false -p:PublishSingleFile=true
        dotnet publish AutoMidiPlayer.WPF -r win-x64 -c Release -o .\portable --self-contained true -p:PublishSingleFile=true

    - name: Zip release
      run: |
        7z a AutoMidiPlayer_${{ steps.tag.outputs.VERSION }}_win-x64_net-install.zip .\install\* -mx9
        7z a AutoMidiPlayer_${{ steps.tag.outputs.VERSION }}_win-x64_portable.zip .\portable\* -mx9

    - name: Create Release
      uses: ncipollo/release-action@v1
      with:
          allowUpdates: true
          omitBodyDuringUpdate: true
          omitNameDuringUpdate: true
          artifacts:
              ./AutoMidiPlayer_${{ steps.tag.outputs.VERSION }}_win-x64_net-install.zip,
              ./AutoMidiPlayer_${{ steps.tag.outputs.VERSION }}_win-x64_portable.zip
          artifactContentType: application/zip
          token: ${{ secrets.GITHUB_TOKEN }}
